### ISSUE TITLE
Import or export not working in theme.js file.

### ISSUE THREAD

**Issue by joshtom** [gperl27/website#16]
Hi, @gperl27 I opened this issue not because something is wrong with this repo but mine. I tried implementing dark-mode with styled-component by following this example https://www.gatsbyjs.org/packages/gatsby-styled-components-dark-mode/ but every time I get stuck trying to export or import in theme.js. The terminal returns this error 
![image](https://user-images.githubusercontent.com/42160061/87731237-e6062780-c7c1-11ea-9d9b-25e9cbdf6761.png)

I don't know what I'm doing wrong
Here is the repo link https://github.com/joshtom/joshuaOlajidev2/tree/DevelopFailed

I'm so sorry If I'm reaching out this way. This is the best way I could reach out. Thanks

**Comment by 01binary** [comment]
I noticed the same thing. He forgot to mention that you need to install `ts-node` and then call this at the top of gatsby-config.js:

```
require("ts-node").register({ files: true })
```

See https://github.com/gperl27/website/blob/master/gatsby-config.js#L2

**Comment by joshtom** [comment]
> I noticed the same thing. He forgot to mention that you need to install `ts-node` + `typescript` and then call this at the top of gatsby-config.js:
> 
> ```
> require("ts-node").register({ files: true })
> ```
> 
> See https://github.com/gperl27/website/blob/master/gatsby-config.js#L2

**Comment by gperl27** [comment]
Hey guys, sorry about being late to this. I'll look to make a more helpful guide on setting up the plugin using TS rather than referencing this repo.

Any other gotchas that you guys ran into?

**Comment by 01binary** [comment]
I loved your work on this, it's awesome - thank you. I tried an implementation of dark mode with styled components myself and couldn't get it working (styles were not rendering in prod), but this library fixed everything.

**Comment by gperl27** [comment]
Glad to hear it helped! Thanks 😄
